export const countries = [
  { name: 'Afganistán', code: 'AF' },
  { name: 'Albania', code: 'AL' },
  { name: 'Alemania', code: 'DE' },
  { name: 'Argelia', code: 'DZ' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Anguila', code: 'AI' },
  { name: 'Antártida', code: 'AQ' },
  { name: 'Antigua y Barbuda', code: 'AG' },
  { name: 'Arabia Saudita', code: 'SA' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Aruba', code: 'AW' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaiyán', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrein', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Bélgica', code: 'BE' },
  { name: 'Belice', code: 'BZ' },
  { name: 'Benín', code: 'BJ' },
  { name: 'Bermudas', code: 'BM' },
  { name: 'Bielorrusia', code: 'BY' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bonaire, San Eustaquio y Saba', code: 'BQ' },
  { name: 'Bosnia y Herzegovina', code: 'BA' },
  { name: 'Botsuana', code: 'BW' },
  { name: 'Brasil', code: 'BR' },
  { name: 'Brunéi', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Bután', code: 'BT' },
  { name: 'Cabo Verde', code: 'CV' },
  { name: 'Camboya', code: 'KH' },
  { name: 'Camerún', code: 'CM' },
  { name: 'Canadá', code: 'CA' },
  { name: 'Catar', code: 'QA' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chequia', code: 'CZ' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Chipre', code: 'CY' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoras', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Congo (República Democrática del)', code: 'CD' },
  { name: 'Corea del Norte', code: 'KP' },
  { name: 'Corea del Sur', code: 'KR' },
  { name: 'Costa de Marfil', code: 'CI' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Croacia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Curazao', code: 'CW' },
  { name: 'Dinamarca', code: 'DK' },
  { name: 'Dominica', code: 'DM' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egipto', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Emiratos Árabes Unidos', code: 'AE' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Eslovaquia', code: 'SK' },
  { name: 'Eslovenia', code: 'SI' },
  { name: 'España', code: 'ES' },
  { name: 'Estados Unidos', code: 'US' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Esuatini', code: 'SZ' },
  { name: 'Etiopía', code: 'ET' },
  { name: 'Filipinas', code: 'PH' },
  { name: 'Finlandia', code: 'FI' },
  { name: 'Fiyi', code: 'FJ' },
  { name: 'Francia', code: 'FR' },
  { name: 'Gabón', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Gibraltar', code: 'GI' },
  { name: 'Granada', code: 'GD' },
  { name: 'Grecia', code: 'GR' },
  { name: 'Groenlandia', code: 'GL' },
  { name: 'Guadalupe', code: 'GP' },
  { name: 'Guam', code: 'GU' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guernsey', code: 'GG' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bisáu', code: 'GW' },
  { name: 'Guinea Ecuatorial', code: 'GQ' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Guayana Francesa', code: 'GF' },
  { name: 'Haití', code: 'HT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hong Kong', code: 'HK' },
  { name: 'Hungría', code: 'HU' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Irak', code: 'IQ' },
  { name: 'Irán', code: 'IR' },
  { name: 'Irlanda', code: 'IE' },
  { name: 'Islandia', code: 'IS' },
  { name: 'Islas Åland', code: 'AX' },
  { name: 'Islas Caimán', code: 'KY' },
  { name: 'Islas Cocos (Keeling)', code: 'CC' },
  { name: 'Islas Cook', code: 'CK' },
  { name: 'Islas Feroe', code: 'FO' },
  { name: 'Islas Georgias del Sur y Sandwich del Sur', code: 'GS' },
  { name: 'Islas Heard y McDonald', code: 'HM' },
  { name: 'Islas Malvinas', code: 'FK' },
  { name: 'Islas Marshall', code: 'MH' },
  { name: 'Islas Marianas del Norte', code: 'MP' },
  { name: 'Islas Pitcairn', code: 'PN' },
  { name: 'Islas Salomón', code: 'SB' },
  { name: 'Islas Turcas y Caicos', code: 'TC' },
  { name: 'Islas Ultramarinas Menores de los Estados Unidos', code: 'UM' },
  { name: 'Islas Vírgenes Británicas', code: 'VG' },
  { name: 'Islas Vírgenes de los Estados Unidos', code: 'VI' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italia', code: 'IT' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japón', code: 'JP' },
  { name: 'Jersey', code: 'JE' },
  { name: 'Jordania', code: 'JO' },
  { name: 'Kazajistán', code: 'KZ' },
  { name: 'Kenia', code: 'KE' },
  { name: 'Kirguistán', code: 'KG' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Laos', code: 'LA' },
  { name: 'Lesoto', code: 'LS' },
  { name: 'Letonia', code: 'LV' },
  { name: 'Líbano', code: 'LB' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libia', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lituania', code: 'LT' },
  { name: 'Luxemburgo', code: 'LU' },
  { name: 'Macao', code: 'MO' },
  { name: 'Macedonia del Norte', code: 'MK' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malasia', code: 'MY' },
  { name: 'Malaui', code: 'MW' },
  { name: 'Maldivas', code: 'MV' },
  { name: 'Malí', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Marruecos', code: 'MA' },
  { name: 'Martinica', code: 'MQ' },
  { name: 'Mauricio', code: 'MU' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mayotte', code: 'YT' },
  { name: 'México', code: 'MX' },
  { name: 'Micronesia', code: 'FM' },
  { name: 'Moldavia', code: 'MD' },
  { name: 'Mónaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Montserrat', code: 'MS' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Níger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Niue', code: 'NU' },
  { name: 'Noruega', code: 'NO' },
  { name: 'Nueva Caledonia', code: 'NC' },
  { name: 'Nueva Zelanda', code: 'NZ' },
  { name: 'Omán', code: 'OM' },
  { name: 'Países Bajos', code: 'NL' },
  { name: 'Pakistán', code: 'PK' },
  { name: 'Palaos', code: 'PW' },
  { name: 'Palestina', code: 'PS' },
  { name: 'Panamá', code: 'PA' },
  { name: 'Papúa Nueva Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Perú', code: 'PE' },
  { name: 'Polinesia Francesa', code: 'PF' },
  { name: 'Polonia', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Puerto Rico', code: 'PR' },
  { name: 'Reino Unido', code: 'GB' },
  { name: 'República Centroafricana', code: 'CF' },
  { name: 'República Dominicana', code: 'DO' },
  { name: 'Reunión', code: 'RE' },
  { name: 'Rumanía', code: 'RO' },
  { name: 'Rusia', code: 'RU' },
  { name: 'Ruanda', code: 'RW' },
  { name: 'Sahara Occidental', code: 'EH' },
  { name: 'Samoa', code: 'WS' },
  { name: 'Samoa Americana', code: 'AS' },
  { name: 'San Bartolomé', code: 'BL' },
  { name: 'San Cristóbal y Nieves', code: 'KN' },
  { name: 'San Marino', code: 'SM' },
  { name: 'San Martín (parte francesa)', code: 'MF' },
  { name: 'San Pedro y Miquelón', code: 'PM' },
  { name: 'San Vicente y las Granadinas', code: 'VC' },
  { name: 'Santa Elena, Ascensión y Tristán de Acuña', code: 'SH' },
  { name: 'Santa Lucía', code: 'LC' },
  { name: 'Santa Sede', code: 'VA' },
  { name: 'Santo Tomé y Príncipe', code: 'ST' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Seychelles', code: 'SC' },
  { name: 'Sierra Leona', code: 'SL' },
  { name: 'Singapur', code: 'SG' },
  { name: 'Sint Maarten (parte neerlandesa)', code: 'SX' },
  { name: 'Siria', code: 'SY' },
  { name: 'Somalia', code: 'SO' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudáfrica', code: 'ZA' },
  { name: 'Sudán', code: 'SD' },
  { name: 'Sudán del Sur', code: 'SS' },
  { name: 'Suecia', code: 'SE' },
  { name: 'Suiza', code: 'CH' },
  { name: 'Surinam', code: 'SR' },
  { name: 'Svalbard y Jan Mayen', code: 'SJ' },
  { name: 'Tailandia', code: 'TH' },
  { name: 'Taiwán', code: 'TW' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Tayikistán', code: 'TJ' },
  { name: 'Territorio Británico del Océano Índico', code: 'IO' },
  { name: 'Territorios Australes Franceses', code: 'TF' },
  { name: 'Timor Oriental', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tokelau', code: 'TK' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trinidad y Tobago', code: 'TT' },
  { name: 'Túnez', code: 'TN' },
  { name: 'Turkmenistán', code: 'TM' },
  { name: 'Turquía', code: 'TR' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Ucrania', code: 'UA' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistán', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Wallis y Futuna', code: 'WF' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Yibuti', code: 'DJ' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabue', code: 'ZW' },
]
